config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :employees

  # Public pages routes
  get '/about', to: 'pages#about_us'
  get '/contact', to: 'pages#contact_us'
  get '/privacy-policy', to: 'pages#privacy_policy'
  get '/terms-and-conditions', to: 'pages#terms_and_conditions'
end

# Rails.application.routes.draw do
#   root 'home#index'
#
#   resources :employees
#   # do
#     # collection do
#     #   post :new, to: 'employees#new'
#     # end
#   # end
#
#   #public pages routes
#   get '/about' => 'pages#about_us'
#   get '/contact' => 'pages#contact_us'
#   get '/privacy-policy' => 'pages#privacy_policy'
#   get '/terms-and-conditions' => 'pages#terms_and_conditions'
#   # get 'pages/about_us'
#   # get 'pages/contact_us'
#   # get 'pages/privacy_policy'
#   # get 'pages/terms_and_conditions'
#   # get  'home/index'
#   # get '/home', to: 'home#index'
#   # get '/home' => 'home#index'
#
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :first_name, :last_name, presence: true
  validates :personal_email, presence: true, uniqueness: true
  validates :city, :state, :country, :pincode, presence: true

  def name
    "#{first_name} #{last_name}".strip
  end

  def full_address
    "#{address_line1} #{address_line_2} #{city} #{state} #{country} #{pincode}".strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path
    else
      render :new
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :middle_name, :last_name, :personal_email, :city, :state, :country, :pincode, :address_line1, :address_line_2)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/index.html.erb
<div class="col-lg-12">
<div class="card rounded-0 mt-5 mb-5">
  <div class="card-body">
<h2 class="text-center">Listing Employees</h2>
  </div>
</div>
<%= link_to "Create New Employee", new_employee_path, class: "btn btn-primary btn-lg mb-4 rounded-0" %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
        <th>Email</th>
        <th>Address</th>
    </tr>
  </thead>
  <tbody>
  <% @employees.each do |employee| %>
  <tr>
<!--    <td><%#= employee.first_name %>  <%#= employee.last_name %></td>-->
<!--    <td><%#= "#{employee.first_name} #{employee.last_name}" %></td>-->
<!--    <td><%#= employee.last_name %></td>-->
    <td><%= employee.name %></td>
    <td><%= employee.personal_email %></td>
    <td><%= employee.full_address %></td>

  </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Create new Employee</h2>
    </div>
  </div>

  <%= form_with model: @employee do |form| %>
    <div class="row">
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :first_name, class: 'mb-2' %>
          <%= form.text_field :first_name, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :middle_name, class: 'mb-2' %>
          <%= form.text_field :middle_name, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :last_name, class: 'mb-2' %>
          <%= form.text_field :last_name, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="form-group">
          <%= form.label :personal_email, class: 'mb-2' %>
          <%= form.text_field :personal_email, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :address_line1, class: 'mb-2' %>
          <%= form.text_field :address_line1, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <%= form.label :address_line_2, class: 'mb-2' %>
          <%= form.text_field :address_line_2, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>

      <div class="col-lg-3">
        <div class="form-group">
          <%= form.label :city, class: 'mb-2' %>
          <%= form.text_field :city, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>

      <div class="col-lg-3">
        <div class="form-group">
          <%= form.label :state, class: 'mb-2' %>
          <%= form.text_field :state, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>

      <div class="col-lg-3">
        <div class="form-group">
          <%= form.label :country, class: 'mb-2' %>
          <%= form.text_field :country, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>

      <div class="col-lg-3">
        <div class="form-group">
          <%= form.label :pincode, class: 'mb-2' %>
          <%= form.text_field :pincode, class: 'form-control form-control-lg rounded-0' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 mt-4">
        <%= form.submit class: "btn btn-primary btn-lg rounded-0" %>
        <%= link_to "Back to Employees", employees_path, class: "btn btn-outline-primary btn-lg rounded-0" %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.erb
<h1 style="color: yellowgreen; background-color: black"><%= @title_text %></h1>
<h1><%= @Subtitle_text %></h1>
  <%#= link_to 'About us', controller: :pages, action: :about_us %>
  <%#= link_to 'About us', about_path, target: '_blank', data: { name: 'about-us', resource: 'pages'} %>
  <%#= link_to 'About us', '/about' %>
  <%#= link_to nil, about_path %>

<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrMitra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/header' %>
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
<%= render 'shared/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


  <script src="https://kit.fontawesome.com/38b8deefe8.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4"> About HR-Mitra</h1>
<%= render 'shared/dummy_content' %>
</div>

<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4"> Contact Us</h1>
  <!--Section: Contact v.2-->
  <section class="mb-4">

    <!--Section heading-->

    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
      a matter of hours to help you.</p>

    <div class="row">

      <!--Grid column-->
      <div class="col-md-9 mb-md-0 mb-5">
        <form id="contact-form" name="contact-form" action="mail.php" method="POST">

          <!--Grid row-->
          <div class="row">

            <!--Grid column-->
            <div class="col-md-6">
              <div class="md-form mb-0">
                <input type="text" id="name" name="name" class="form-control">
                <label for="name" class="">Your name</label>
              </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6">
              <div class="md-form mb-0">
                <input type="text" id="email" name="email" class="form-control">
                <label for="email" class="">Your email</label>
              </div>
            </div>
            <!--Grid column-->

          </div>
          <!--Grid row-->

          <!--Grid row-->
          <div class="row">
            <div class="col-md-12">
              <div class="md-form mb-0">
                <input type="text" id="subject" name="subject" class="form-control">
                <label for="subject" class="">Subject</label>
              </div>
            </div>
          </div>
          <!--Grid row-->

          <!--Grid row-->
          <div class="row">

            <!--Grid column-->
            <div class="col-md-12">

              <div class="md-form">
                <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                <label for="message">Your message</label>
              </div>

            </div>
          </div>
          <!--Grid row-->

        </form>

        <div class="text-center text-md-left">
          <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
        </div>
        <div class="status"></div>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-3 text-center">
        <ul class="list-unstyled mb-0">
          <li><i class="fas fa-map-marker-alt fa-2x"></i>
            <p>San Francisco, CA 94126, USA</p>
          </li>

          <li><i class="fas fa-phone mt-4 fa-2x"></i>
            <p>+ 01 234 567 89</p>
          </li>

          <li><i class="fas fa-envelope mt-4 fa-2x"></i>
            <p>contact@mdbootstrap.com</p>
          </li>
        </ul>
      </div>
      <!--Grid column-->

    </div>

  </section>
  <!--Section: Contact v.2-->
</div>

app/views/pages/privacy_policy.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4"> Privacy Policy </h1>
  <%= render 'shared/dummy_content' %>
</div>

<%= render 'shared/links' %>

app/views/pages/terms_and_conditions.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4"> Terms and Conditions </h1>
  <%= render 'shared/dummy_content' %>
</div>

<%= render 'shared/links' %>

app/views/shared/_dummy_content.html.erb
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
    <span>Get connected with us on social networks:</span>
  </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
    <%= link_to 'HR-Mitra', root_path, class: 'navbar_brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<h1>HR-Mitra </h1>
  <div style="background-color: black">
<%= link_to 'About Us', about_path, target: '_blank', style: 'color:yellow' %>
<%= link_to 'Contact Us', contact_path, target: '_blank', style: 'color:yellow' %>
<%= link_to 'Privacy Policy', privacy_policy_path, target: '_blank', style: 'color:yellow' %>
<%= link_to 'Terms and Conditions', terms_and_conditions_path, target: '_blank', style: 'color:yellow' %>
  </div>